// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsPro.Models;

#nullable disable

namespace SportsPro.Migrations
{
    [DbContext(typeof(SportsProContext))]
    [Migration("20240211172040_UpdateProductsData")]
    partial class UpdateProductsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsPro.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Code = "TRNY10",
                            CreatedDateTime = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tournament Master 1.0",
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Code = "LEAG10",
                            CreatedDateTime = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "League Scheduler 1.0",
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Code = "LEAGD10",
                            CreatedDateTime = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "League Scheduler Deluxe 1.0",
                            YearlyPrice = 7.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Code = "DRAFT10",
                            CreatedDateTime = new DateTime(2018, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Draft Manager 1.0",
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Code = "TEAM10",
                            CreatedDateTime = new DateTime(2020, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Team Manager 1.0",
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Code = "TRNY20",
                            CreatedDateTime = new DateTime(2021, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tournament Master 2.0",
                            YearlyPrice = 5.99m
                        },
                        new
                        {
                            ProductId = 7,
                            Code = "DRAFT20",
                            CreatedDateTime = new DateTime(2020, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Draft Manager 2.0",
                            YearlyPrice = 5.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
